### ISSUE TITLE
brak połaczenia  depictor > GRBL

### ISSUE THREAD

**Issue by qulet** [Iqwertz/Depictor#173]
Depictor zainstalowałsię poprawnie . Procesing - przetwarzanie obrazu działa. Nie można nawiązać połączenia rasbperry - arduino uno po kablu USB.

**Comment by qulet** [comment]
Does the arduino show up in the settings under "serial port"?Thank you for contacting us, we've met on Discord before, you helped me with an earlier version of Depictor. Now I have changed Rasbper pi to 4 and reinstalled Depictor. Yes serial port is visible in settings.I enclose prtscr.   Discord  rozmowaMarek#3226   JuHuWysłane z aplikacji Poczta dla systemu Windows  Od: IqwertzWysłano: wtorek, 6 czerwca 2023 19:10Do: Iqwertz/DepictorDW: Marek; AuthorTemat: Re: [Iqwertz/Depictor] brak połaczenia depictor > GRBL (Issue #173) Does the arduino show up in the settings under "serial port"?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Iqwertz** [comment]
Yes I think I can remember :) 
When you try to select a serial port, what are the available ports that are listed?

**Comment by Iqwertz** [comment]
Sorry cant really view ypur message, since it is really weirdly formatted! Could you try to comment from the github website and write in englisch?

**Comment by qulet** [comment]
![setting_4](https://github.com/Iqwertz/Depictor/assets/30979927/b9f7a915-4419-4b33-826e-f4eb571e84ed)
Ports visible in my settings:

**Comment by qulet** [comment]
I posted a comment from the GITHUB page Wysłane z aplikacji Poczta dla systemu Windows  Od: IqwertzWysłano: środa, 7 czerwca 2023 12:51Do: Iqwertz/DepictorDW: Marek; AuthorTemat: Re: [Iqwertz/Depictor] brak połaczenia depictor > GRBL (Issue #173) Sorry cant really view ypur message, since it is really weirdly formatted! Could you try to comment from the github website and write in englisch?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by qulet** [comment]
![Terminal](https://github.com/Iqwertz/Depictor/assets/30979927/ed7d00cc-880b-4dd5-9968-0a6d4a7e3080)
